imprpfailure protocol for element operations
forensic-architecture/mtriage pull request #57
Opened 2019-06-07 11:52 UTC by samludford

2019-06-07 12:13 UTC, samludford commented
There's some duplication of error handling logic in selectors and analysers, since retrieving and analysing an element are treated the same way (i.e. as general element operations). I considered putting this logic in another ABC which both selector and analyser would inherit from, but this felt like over-engineering in this case so I left it as is. It may be worth doing that (or something equivalent) if we develop the error handling protocol further.

2019-06-10 14:37 UTC, breezykermo requested changes

2019-06-10 14:37 UTC, breezykermo commented on src/lib/analysers/convert_audio/main.py
> +            ["ffmpeg", "-y", "-i", audio, f"{dest}/{key}.{output_ext}"],
does this flag mean that `ffmpeg` will relay logs?

2019-06-10 14:37 UTC, breezykermo commented on src/lib/common/exceptions.py
> +        super().__init__(f"{msg} - attempt retry")
I know I suggested these titles, but maybe we can make them more descriptive/less verbose. What do you think of `ElementShouldSkipError` and `ElementShouldRetryError` ?

2019-06-10 15:48 UTC, breezykermo approved these changes

2019-06-10 15:48 UTC, merged